#!/bin/bash
# Runs INSIDE the CentOS server (via ssh, as root/sudo), invoked by
# configure_and_start.sh.
#
# This VM's public hostname has no wildcard DNS, so there's no spare
# subdomain to give this orchestrator its own Nginx vhost/certificate. It
# instead piggybacks on dlpx-mcp-remote-server's existing vhost
# (/etc/nginx/conf.d/dlpx-mcp.conf), adding a `location /servicenow-webhook`
# block that proxies to this app (127.0.0.1:8940), reusing that project's
# hostname and TLS certificate.
#
# Idempotent: removes any previously inserted block (by marker) before
# re-adding it, so running this again after an app update is a no-op change.
#
# IMPORTANT — this couples the two projects: dlpx-mcp-remote-server's own
# installer rewrites dlpx-mcp.conf from scratch on every install (see that
# project's docs/architecture.md), which wipes the block this script adds.
# If dlpx-mcp-remote-server is ever reinstalled/updated on this host,
# re-run this orchestrator's "Install" option (./orchestrator.sh 1) to
# reapply it.
set -euo pipefail

MCP_CONF="/etc/nginx/conf.d/dlpx-mcp.conf"
BEGIN_MARKER="# BEGIN dlpx-servicenow-orchestrator"
END_MARKER="# END dlpx-servicenow-orchestrator"

log() { echo "[patch_shared_nginx] $*"; }

if [ "$(id -u)" -ne 0 ]; then
    echo "This script must run as root (sudo)." >&2
    exit 1
fi

if [ ! -f "$MCP_CONF" ]; then
    echo "$MCP_CONF not found — dlpx-mcp-remote-server must be installed on this host first." >&2
    exit 1
fi

if ! grep -qE 'ssl_dhparam .*managed by Certbot' "$MCP_CONF"; then
    echo "Could not find the expected Certbot-managed anchor line in $MCP_CONF." >&2
    echo "This usually means dlpx-mcp-remote-server hasn't issued its TLS certificate yet" >&2
    echo "(no 'listen 443 ssl' block present). Finish that project's install first." >&2
    exit 1
fi

backup="$MCP_CONF.bak.$(date +%Y%m%d%H%M%S)"
cp "$MCP_CONF" "$backup"

log "Removing any previous dlpx-servicenow-orchestrator block (idempotent)..."
sed -i "/$BEGIN_MARKER/,/$END_MARKER/d" "$MCP_CONF"

log "Inserting the /servicenow-webhook location block..."
awk -v begin="$BEGIN_MARKER" -v end="$END_MARKER" '
    {
        print
        if ($0 ~ /ssl_dhparam .*managed by Certbot/) {
            print ""
            print "    " begin
            print "    # Managed by dlpx-servicenow-orchestrator'"'"'s installer. Reapply via"
            print "    # that project'"'"'s ./orchestrator.sh Install option if this file is"
            print "    # ever regenerated by dlpx-mcp-remote-server'"'"'s own installer."
            print "    location /servicenow-webhook {"
            print "        proxy_pass http://127.0.0.1:8940/servicenow-webhook;"
            print "        proxy_http_version 1.1;"
            print "        proxy_set_header Host $host;"
            print "        proxy_set_header X-Real-IP $remote_addr;"
            print "        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;"
            print "        proxy_set_header X-Forwarded-Proto $scheme;"
            print "    }"
            print "    " end
        }
    }
' "$MCP_CONF" > "$MCP_CONF.new"
mv "$MCP_CONF.new" "$MCP_CONF"

log "Validating Nginx configuration..."
if ! nginx -t; then
    echo "nginx -t failed after patching $MCP_CONF — restoring the previous version from $backup." >&2
    cp "$backup" "$MCP_CONF"
    exit 1
fi

systemctl reload nginx
log "Shared Nginx vhost patched successfully (backup kept at $backup)."
